write_register:
  fields:
    register:
      example: "16384"
      required: true
      selector:
        number:
          min: 0
          max: 65535 
          mode: box

    value:
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 65535 
          mode: box

    modbus_function:
      example: "6"
      required: false
      selector:
        number:
          min: 0
          max: 255  
          mode: box

write_multiple_registers:
  fields:
    registers:
      example: "108, 142"
      required: true
      selector:
        text:
          multiline: false

    values:
      example: "140, 1"
      required: true
      selector:
        text:
          multiline: false
